### ISSUE TITLE
tests don't typecheck

### ISSUE THREAD

**Issue by ocramz** [ttuegel/sparse-linear#1]
GHC 7.8.3: after installation, I ran `ghci LinearAlgebra.hs`, log follows

[1 of 1] Compiling Test.LinearAlgebra ( LinearAlgebra.hs, interpreted )

LinearAlgebra.hs:37:16:
    Could not deduce (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox a)
      arising from a use of ‘><’
    from the context (Arbitrary a, Num a, Orient or, Unbox a)
      bound by the type signature for
                 arbitraryMatrix :: (Arbitrary a, Num a, Orient or, Unbox a) =>
                                    Int -> Int -> Gen (Matrix or a)
      at LinearAlgebra.hs:(29,6)-(30,36)
    Possible fix:
      add (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox
             a) to the context of
        the type signature for
          arbitraryMatrix :: (Arbitrary a, Num a, Orient or, Unbox a) =>
                             Int -> Int -> Gen (Matrix or a)
    In the expression: nr >< nc
    In the second argument of ‘($)’, namely ‘(nr >< nc) triples’
    In a stmt of a 'do' block: return $ (nr >< nc) triples

LinearAlgebra.hs:60:67:
    Could not deduce (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox a)
      arising from a use of ‘show’
    from the context (Arbitrary a, Num a, Orient or, Show a, Unbox a)
      bound by the type signature for
                 checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
                                Gen (Matrix or a) -> Property
      at LinearAlgebra.hs:(56,6)-(57,34)
    or from (Testable prop)
      bound by the inferred type of
               dieUnless :: Testable prop => [Char] -> prop -> Property
      at LinearAlgebra.hs:60:7-75
    Possible fix:
      add (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox
             a) to the context of
        the inferred type of
        dieUnless :: Testable prop => [Char] -> prop -> Property
        or the type signature for
             checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
                            Gen (Matrix or a) -> Property
    In the second argument of ‘(++)’, namely ‘show mat’
    In the second argument of ‘(++)’, namely ‘" " ++ show mat’
    In the second argument of ‘(++)’, namely ‘str ++ " " ++ show mat’

LinearAlgebra.hs:61:21:
    Could not deduce (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox a)
      arising from a use of ‘slice’
    from the context (Arbitrary a, Num a, Orient or, Show a, Unbox a)
      bound by the type signature for
                 checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
                                Gen (Matrix or a) -> Property
      at LinearAlgebra.hs:(56,6)-(57,34)
    Possible fix:
      add (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox
             a) to the context of
        the type signature for
          checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
                         Gen (Matrix or a) -> Property
    In the first argument of ‘map’, namely ‘(slice mat)’
    In the expression: map (slice mat) [0 .. (odim - 1)]
    In an equation for ‘slices’:
        slices = map (slice mat) [0 .. (odim - 1)]

LinearAlgebra.hs:62:23:
    Could not deduce (V.Vector
                        vector-0.10.9.1:Data.Vector.Unboxed.Base.Vector (Int, a))
      arising from a use of ‘V.unzip’
    from the context (Arbitrary a, Num a, Orient or, Show a, Unbox a)
      bound by the type signature for
                 checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
                                Gen (Matrix or a) -> Property
      at LinearAlgebra.hs:(56,6)-(57,34)
    In the second argument of ‘($)’, namely ‘V.unzip entries’
    In the expression: fst $ V.unzip entries
    In an equation for ‘indices’: indices = fst $ V.unzip entries
Failed, modules loaded: none.

**Comment by ttuegel** [comment]
You must have built the library with a different version of `vector` than the one `ghci` is using. That is clear from the errors, which are all of the form:

```
Could not deduce (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox a)
arising from a use of ‘slice’
from the context (Arbitrary a, Num a, Orient or, Show a, Unbox a)
bound by the type signature for
checkMatrix :: (Arbitrary a, Num a, Orient or, Show a, Unbox a) =>
Gen (Matrix or a) -> Property
at LinearAlgebra.hs:(56,6)-(57,34)
Possible fix:
add (vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox a) to the context
```

Notice, the context contains the constraint `Unbox`, but `ghci` is complaining it does not contain the constraint `vector-0.10.9.1:Data.Vector.Unboxed.Base.Unbox`.

You can run the test suite with `cabal test`, and you will see that there is no problem with the test suite. If you want to load the test suite into `ghci`, I recommend using `cabal repl` instead, especially if you are using sandboxes.

**Comment by ocramz** [comment]
Yes, it must be the case. Sorry for opening the bug and thank you for the clarifications.
However I still don't understand why this would happen. I.e., I'm working in OSX, and it seems like the main (non-sandbox) library is spread across two dirs; the following is the output of `ghc-pkg list vector` :

/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/package.conf.d
   vector-0.10.9.1
~/.ghc/x86_64-darwin-7.8.3/package.conf.d
   vector-0.10.12.2

`cabal repl` loads everything fine, however, even when the ambient directory is not a sandbox (cabal 1.22)

I would really love to get rid of this state of things and having a consistent Haskell installation, could you offer any pointers?

**Comment by ocramz** [comment]
(I should add that I don't use sandboxes as first option because of the huge dependency bloat they create every time.)

**Comment by ttuegel** [comment]
This happens because `sparse-linear` is being built against the older `vector` version, which means that one of its dependencies must have been built before you installed the new `vector`, or one of its dependencies must be installed in the system-wide package database. (System-wide packages cannot depend on user packages.)

This is exactly the type of problem sandboxes were designed to prevent. When using a sandbox, Cabal does extra work to ensure that dependencies are always consistent across all packages in the sandbox. This cannot be done outside a sandbox, where reinstalls are dangerous. I would recommend using sandboxes.

To mitigate the overhead of sandboxes, you can share sandboxes between projects. For example, I sometimes share a sandbox between the 3 projects in the `sparse-linear` repository. You can type `cabal sandbox init` anywhere (even outside a Cabal project) and it will create a sandbox there. A sandbox consists of a hidden directory, `.cabal-sandbox`, and a sandbox config file, `cabal.sandbox.config`. Whenever you want to use that sandbox in a project, just make a symbolic link to the `cabal.sandbox.config` file in the project directory.

You could even go so far as to create a single sandbox that you use for all of your Haskell work. That would be like replacing your user package database with a sandbox, which has stricter dependency rules. I wouldn't recommend going that far, though, because of the stricter dependency rules.

Note, however: to take advantage of a sandbox, you have to use the `cabal` tool. Plain `ghc`, `ghci`, and `ghc-pkg` don't know about sandboxes.

**Comment by ocramz** [comment]
Thank you so much for all this information. I'm still inching my way up the Haskell learning curve, and I'm impatient to try out some fancy libraries for my scientific work, but first I have to solve all these bookkeeping issues.
